# Generated by Django 3.1.6 on 2021-02-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='allVote',
            field=models.IntegerField(default=0),
        ),
    ]
